### ISSUE TITLE
Usage of Operations as "railways"

### ISSUE THREAD

**Issue by akxcv** [0exp/smart_core#7]
Suppose I want the following behaviour:

```ruby
class UserRegistration < SmartCore::Operation
  param :user

  def call
    validate
    save
  end

  private

  def validate
    UserValidation.call(user) # another Operation that returns either a Success or a Failure
  end

  def save
    # persistence logic that also returns a Success or a Failure
  end
end
```

```ruby
UserRegistration.call(invalid_user) # => Failure(:email_invalid, :passwords_do_not_match)
UserRegistration.call(valid_user) # => Failure(:database_connection_error)
UserRegistration.call(valid_user) # => Success(persisted_user)
```

Only the last `Success` is returned, and on any `Failure`, the execution stops.

Could this be cleanly done with SmartCore? An example of code achieving this would be helpful. Also, I believe this to be a good use case for the library.

**Comment by nulldef** [comment]
I think there you shouldn't pass a `user` variable to `validate(user)` and `save(user)`, 'cause it already exists in this context.

**Comment by akxcv** [comment]
Sure, but that's not the point of this issue.

**Comment by akxcv** [comment]
We could maybe introduce a separate abstract class, like `SmartCore::Railway`? I'm happy to write out an API for it if we decide that this is a good idea.

**Comment by 0exp** [comment]
Moved to `ROADMAP` section.
